const features = {
    free: {
        planName: 'Free',
        minutesPerMonth: true, // Availability of this feature in Free plan
        renderQuality: true,
        importWith: true,
        importIntegrations: false,
        aiSubtitles: true,
        multiLingual: false,
        chapters: true,
        creditSaver: false,
        intelliclips: true,
        viralityScore: true,
        bulkExport: false,
        multipleAspectRatio: true,
        defaultTemplates: true,
        createCustomClip: true,
        cutmagic: false,
        autoEmoji: false,
        fancyCaptions: false,
        progressBar: true,
        stockMedia: false,
        backgroundAudio: false,
        customBackgrounds: false,
    },
    essential: {
        planName: 'Essential',
        minutesPerMonth: true,
        renderQuality: true,
        importWith: true,
        importIntegrations: true,
        aiSubtitles: true,
        multiLingual: false,
        chapters: false,
        creditSaver: true,
        intelliclips: true,
        viralityScore: true,
        bulkExport: 'Up to 5 exports',
        multipleAspectRatio: true,
        defaultTemplates: true,
        createCustomClip: true,
        cutmagic: true,
        autoEmoji: false,
        fancyCaptions: false,
        progressBar: true,
        stockMedia: true,
        backgroundAudio: true,
        customBackgrounds: false,
    },
    growth: {
        planName: 'Growth',
        minutesPerMonth: true,
        renderQuality: true,
        importWith: true,
        importIntegrations: true,
        aiSubtitles: true,
        multiLingual: true,
        chapters: false,
        creditSaver: true,
        intelliclips: true,
        viralityScore: true,
        bulkExport: 'Unlimited exports',
        multipleAspectRatio: true,
        defaultTemplates: true,
        createCustomClip: true,
        cutmagic: true,
        autoEmoji: true,
        fancyCaptions: true,
        progressBar: true,
        stockMedia: true,
        backgroundAudio: true,
        customBackgrounds: false,
    },
    custom: {
        planName: 'Custom',
        minutesPerMonth: true,
        renderQuality: true,
        importWith: true,
        importIntegrations: true,
        aiSubtitles: true,
        multiLingual: true,
        chapters: false,
        creditSaver: true,
        intelliclips: true,
        viralityScore: true,
        bulkExport: 'Unlimited exports',
        defaultTemplates: true,
        createCustomClip: true,
        cutmagic: true,
        autoEmoji: true,
        fancyCaptions: true,
        progressBar: true,
        stockMedia: true,
        backgroundAudio: true,
        customBackgrounds: 'Custom plan allows custom backgrounds',
    },
}
